console.group("Group One");
console.log("Messege One");
console.log("Messege Two");
console.group("Child group");
console.log("Messege One");
console.log("Messege Two");
console.group("Grand child group");
console.log("Messege One");
console.log("Messege Two");
console.groupEnd();
console.groupEnd();
console.groupEnd();
console.group("Group Two");
console.log("Messege One");
console.log("Messege Two");